name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write SSH key to file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy project to EC2
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

    - name: SSH, write .env, and deploy Docker
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app
          # Create .env file from GitHub secrets
          cat > .env << ENV_EOF
          CHUNK_OVERLAP=${{ secrets.CHUNK_OVERLAP }}
          CHUNK_SIZE=${{ secrets.CHUNK_SIZE }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL=${{ secrets.GROQ_MODEL }}
          HUGGINGFACE_MODEL=${{ secrets.HUGGINGFACE_MODEL }}
          MAX_FILE_SIZE=${{ secrets.MAX_FILE_SIZE }}
          SUPPORTED_FORMATS=${{ secrets.SUPPORTED_FORMATS }}
          ENV_EOF

          # Deploy Docker
          docker compose down --remove-orphans
          docker compose build
          docker compose up -d
        EOF
