name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Verify EC2_HOST secret
      run: |
        if [ -z "${{ secrets.EC2_HOST }}" ]; then
          echo "ERROR: EC2_HOST secret is empty!"
          exit 1
        else
          echo "EC2_HOST is set"
        fi

    - name: Write SSH key to file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy project to EC2
      run: |
        echo "Deploying to ${{ secrets.EC2_HOST }}"
        rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

    - name: SSH and deploy Docker
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app
          docker compose down --remove-orphans
